### ISSUE TITLE
Portfolio deploy environment in Hub missing packages - netlify?

### ISSUE THREAD

**Issue by tiffanychu90** [cal-itp/data-analyses#205]
Portfolio deploy erroring, possibly because of packages not grabbed in `shared_utils`? `shared_utils` doesn't actually install `intake`, since `intake` is already included in the Hub environment.  But `intake` is reading from a `catalog.yml` checked into the repo. **Update: installing `shared_utils` in the terminal at the beginning of the session makes this error go away**

The Hub also might need `netlify` to be installed in its environment?

Running this means the build is completed, but the deploy has an error: `python portfolio/portfolio.py build parallel_corridors --no-execute-papermill --deploy` in the terminal instead results in this error:

```
The HTML pages are in _build/html.

===============================================================================

Finished generating HTML for book.
Your book's HTML pages are here:
    _build/html/
You can look at your book by opening this file in a browser:
    _build/html/index.html
Or paste this line directly into your browser bar:
    file:///home/jovyan/data-analyses/portfolio/parallel_corridors/_build/html/index.html            

===============================================================================

Running deploy:
netlify deploy --site=cal-itp-data-analyses --dir=portfolio/parallel_corridors/_build/html/ --alias=parallel_corridors
Traceback (most recent call last):
  File "/home/jovyan/data-analyses/portfolio/portfolio.py", line 311, in <module>
    app()
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/jovyan/data-analyses/portfolio/portfolio.py", line 307, in build
    subprocess.run(args).check_returncode()
  File "/opt/conda/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/conda/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'netlify'
```

**Comment by atvaccaro** [comment]
@charlie-costanzo want to close this?

**Comment by charlie-costanzo** [comment]
> @charlie-costanzo want to close this?

yeppp
